language: php
sudo: false
php:
  - 7.1
  - 7.2

addons:
  sonarcloud:
    organization: "getolympus"
    token:
      secure: "j1c4AvUsI8zrUPm7H1JEjKc1zo61yZrVpkxExSHtsxUSJtF2LlT8a+FTMwJmN8Z3oTU//2Ofn/KDKxY6a8YbrReyvlBDmCq/g2IMcminwwW16wlrW0k2cAu8lGpGl20+hCauFqPEgMgaOG4LQjXKDylHnLPn4vkyD4lpMmeLZmrk6FCZYvF1zvkTcX7PgTTPj6KgEy8AAG7HAkEvy8bXRsQIRNhUNA8xQYtBSih0B73itOwKqwAokSb1RkGl8aeZflMZvqZffQKyCIx5GIgYZGitZ0C5YdXcY0zAbli5kM0xH5dQzKgaez/goc3RTdk1gQK/BAHUsAJfsm1fiscUy+EiFpYk09KxQHq9/m5x7g1Box0ZNPVyUjntIsa3CB0DAuye3PFNhj32Q3zngfRZH3m2Odmw1V9+sWrGi1+5XDsbkV4ZHGGmFO5uMeRzy9G5zvHo32XzqkhOM9yliE6jz4y5Xx+9My2FBfNFeLllPNrczvWzqFavBtlq9krrfj3UmtK19gEvs6dgPT7smc13/jL9ifLkRzj4p+gvpO6RjePyfuR/b8a74FOM0EFowWpVH/oYaPfNkdmZNAHJNyQriSDFgzhLpP4WRD3/cmmE/keFzI6i+qSkOEh/xvE8O1ixPTVFekPQ6cKFWtXsn3H1J5w2jOhbX/h/0lcsdNBTAJc="

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - "$HOME/.composer/cache"
    - app/cache
    - vendor

before_install:
  - composer self-update

install:
  - composer install -o --prefer-dist --no-interaction

script:
  - composer test
  - sonar-scanner
