language: php
sudo: false
php:
  - 7.2
  - 7.3

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - "$HOME/.composer/cache"
    - app/cache
    - vendor

before_install:
  - composer self-update

install:
  - composer install -o --prefer-dist --no-interaction

script:
  - composer test
